// actionTypes.js
export const actionTypes = {


  // Product actions
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_CATEGORIES: "SET_CATEGORIES",
  SET_SUBCATEGORIES: "SET_SUBCATEGORIES",

  // Shipping actions
  SET_PROVINCES: "SET_PROVINCES",
  SET_CITIES: "SET_CITIES",
  SET_SELECTED_PROVINCE: "SET_SELECTED_PROVINCE",
  SET_SELECTED_CITY: "SET_SELECTED_CITY",
  SET_COST: "SET_COST",
  SET_SELECTED_SERVICE: "SET_SELECTED_SERVICE",
  SET_METHOD: "SET_METHOD",
  SET_LOADING_COST: "SET_LOADING_COST",

  // Token and loading
  SET_TOKEN: "SET_TOKEN",
  SET_LOADING: "SET_LOADING",
  SET_LOADING_SEARCH: "SET_LOADING_SEARCH",

  // Form and search
  SET_FORM_DATA: "SET_FORM_DATA",
  SET_SEARCH: "SET_SEARCH",
  TOGGLE_SHOW_SEARCH: "TOGGLE_SHOW_SEARCH",

  // Pagination
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
};
